# Generated by Django 4.2.6 on 2023-10-19 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Venue_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event_id', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('Venue_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue', to='event_managment.venue')),
            ],
        ),
    ]
