# Generated by Django 4.2.6 on 2023-10-20 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_managment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
