# Generated by Django 4.2.6 on 2023-10-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_managment', '0005_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
